### ISSUE TITLE
Incorrect warning about quotes in English statement

### ISSUE THREAD

**Issue by alexeydergunov** [Codeforces/polygon-issue-tracking#427] opened 2020-03-31 15:06 UTC
Create a problem with the following legend:
```
``increase all elements in the segment $[l_j, r_j]$ by $v_j$''.
```
ER: no warnings
AR: warning: use quotes like `text' instead of ''. in section 'legend' of english statement

**Comment by MikeMirzayanov** [comment] 2021-06-23 14:20
Can't reproduce it now. Probably, it is fixed now. Can you check it?

**Comment by alexeydergunov** [comment] 2021-06-25 14:52
Now it is not shown inside a problem, but is shown on a contest page.

**Closed as completed** 2021-07-09 13:38 UTC
Labels: statements
