### ISSUE TITLE
More feedback when changing solution language

### ISSUE THREAD

**Issue by kgeorgiy** [Codeforces/polygon-issue-tracking#386] opened 2019-10-30 06:02 UTC
When changing solution language, no feedback is given except quick page reload. It is not obvious, whether the change was applied or not.

Possible solution: highlight changed language after page reload.

**Comment by MikeMirzayanov** [comment] 2020-05-28 11:52
Can't reproduce. Probably, fixed now.

**Closed as completed by MikeMirzayanov** 2020-05-28 11:52 UTC
Labels: ui/ux
